"""CMS domain Pydantic V2 schemas.

Follows RORO: separate request models from response models.
All fields carry Field(description=...) for full OpenAPI/Swagger documentation.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.enums import ContentType, PostStatus, PostVisibility


# ---------------------------------------------------------------------------
# Shared sub-objects
# ---------------------------------------------------------------------------


class MediaItem(BaseModel):
    """One media attachment (image, video, etc.)."""

    model_config = ConfigDict(str_strip_whitespace=True)

    url: str = Field(description="CDN URL of the processed media asset.")
    type: str = Field(description="MIME type, e.g. 'image/webp' or 'video/mp4'.")
    thumbnail: str | None = Field(default=None, description="Thumbnail URL (video posts only).")
    asset_id: str | None = Field(default=None, description="Media service asset ID for playback metadata lookup.")


class LinkPreviewObject(BaseModel):
    """Open-Graph preview scraped server-side for LINK posts."""

    model_config = ConfigDict(str_strip_whitespace=True)

    url: str = Field(description="Canonical URL of the linked page.")
    og_title: str | None = Field(default=None, description="Open Graph title.")
    og_image: str | None = Field(default=None, description="Open Graph image URL.")
    og_description: str | None = Field(default=None, description="Open Graph description.")


# ---------------------------------------------------------------------------
# Post request schemas
# ---------------------------------------------------------------------------


class CreatePostRequest(BaseModel):
    """Request body for creating a new post.

    WEBINAR_CARD and COURSE_CARD are auto-generated by external services (MS-3/MS-4)
    and must not be created via this endpoint.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    content_type: ContentType = Field(
        description=(
            "Post format. User-creatable types: TEXT, IMAGE, VIDEO, LINK. "
            "WEBINAR_CARD, COURSE_CARD are system-generated. REPOST uses /interactions/repost."
        )
    )
    title: str | None = Field(
        default=None,
        max_length=300,
        description="Optional title (max 300 chars).",
    )
    body: str | None = Field(
        default=None,
        max_length=5000,
        description="Rich-text body (max 5,000 chars).",
    )
    media_urls: list[MediaItem] | None = Field(
        default=None,
        description=(
            "Media attachments. IMAGE: 1–10 items. VIDEO: exactly 1. "
            "Not applicable to TEXT or LINK."
        ),
    )
    link_preview: LinkPreviewObject | None = Field(
        default=None,
        description="OG preview. Required for LINK posts.",
    )
    visibility: PostVisibility = Field(
        default=PostVisibility.PUBLIC,
        description="Audience: PUBLIC, VERIFIED_ONLY, or FOLLOWERS_ONLY.",
    )
    status: PostStatus = Field(
        default=PostStatus.DRAFT,
        description="Initial state. Accepted values: DRAFT or PUBLISHED.",
    )
    specialty_tags: list[str] | None = Field(
        default=None,
        description="Medical specialty tags for discovery.",
    )
    channel_id: UUID | None = Field(
        default=None,
        description="Optional channel to assign this post to.",
    )

    @field_validator("status")
    @classmethod
    def _initial_status_must_be_draft_or_published(cls, v: PostStatus) -> PostStatus:
        if v not in (PostStatus.DRAFT, PostStatus.PUBLISHED):
            raise ValueError("Initial status must be DRAFT or PUBLISHED.")
        return v

    @field_validator("media_urls")
    @classmethod
    def _max_ten_media_items(cls, v: list[MediaItem] | None) -> list[MediaItem] | None:
        if v is not None and len(v) > 10:
            raise ValueError("A post may have at most 10 media attachments.")
        return v


class UpdatePostRequest(BaseModel):
    """PATCH body for editing a published or drafted post.

    All fields are optional. Only supplied fields are updated.
    Editing a PUBLISHED or EDITED post automatically takes a version snapshot
    and transitions the status to EDITED.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    title: str | None = Field(default=None, max_length=300, description="New title.")
    body: str | None = Field(default=None, max_length=5000, description="New body text.")
    media_urls: list[MediaItem] | None = Field(default=None)
    link_preview: LinkPreviewObject | None = Field(default=None)
    visibility: PostVisibility | None = Field(default=None)
    specialty_tags: list[str] | None = Field(default=None)
    channel_id: UUID | None = Field(default=None)


class PostRestoreRequest(BaseModel):
    """Request body to restore a specific historical version of a post."""

    version_number: int = Field(
        ge=1,
        description="Version number to restore. Retrieve available versions from GET /cms/posts/{id}/versions.",
    )


# ---------------------------------------------------------------------------
# Channel request schemas
# ---------------------------------------------------------------------------


class CreateChannelRequest(BaseModel):
    """Request body for creating a new channel."""

    model_config = ConfigDict(str_strip_whitespace=True)

    name: str = Field(min_length=1, max_length=150, description="Unique channel display name.")
    slug: str | None = Field(
        default=None,
        max_length=150,
        description="URL-safe slug (lowercase letters, digits, hyphens). Auto-generated if omitted.",
    )
    description: str | None = Field(default=None, description="Channel bio / description.")
    logo_url: str | None = Field(
        default=None, max_length=500, description="CDN URL of the channel logo."
    )


class UpdateChannelRequest(BaseModel):
    """PATCH body for updating a channel (owner only)."""

    model_config = ConfigDict(str_strip_whitespace=True)

    name: str | None = Field(default=None, max_length=150)
    description: str | None = Field(default=None)
    logo_url: str | None = Field(default=None, max_length=500)
    is_active: bool | None = Field(
        default=None,
        description="Set false to deactivate the channel without deleting it.",
    )


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class ChannelResponse(BaseModel):
    """Public channel representation."""

    model_config = ConfigDict(from_attributes=True)

    channel_id: UUID = Field(description="Unique channel identifier.")
    name: str
    slug: str = Field(description="URL-safe channel identifier used in links.")
    description: str | None
    logo_url: str | None
    owner_id: UUID = Field(description="User ID of the channel owner (identity_db reference).")
    is_active: bool
    created_at: datetime


class PostResponse(BaseModel):
    """Full post representation returned by CMS and feed endpoints."""

    model_config = ConfigDict(from_attributes=True)

    post_id: UUID
    author_id: UUID = Field(description="User ID of the post author (identity_db reference).")
    content_type: ContentType
    title: str | None
    body: str | None
    media_urls: list[dict] | None = Field(
        default=None,
        description="Array of {url, type, thumbnail} objects.",
    )
    link_preview: dict | None = Field(
        default=None,
        description="Object: {url, og_title, og_image, og_description}.",
    )
    visibility: PostVisibility
    status: PostStatus = Field(
        description=(
            "Lifecycle: DRAFT (author-only) | PUBLISHED (live) | "
            "EDITED (live, modified at least once) | "
            "SOFT_DELETED (hidden 30d, restorable) | HIDDEN_BY_ADMIN (admin action)."
        )
    )
    specialty_tags: list[str] | None
    like_count: int
    comment_count: int
    share_count: int
    bookmark_count: int
    version: int = Field(description="Monotonically incrementing edit counter.")
    channel_id: UUID | None
    channel: ChannelResponse | None = Field(
        default=None, description="Inline channel when post belongs to one."
    )
    original_post_id: UUID | None = Field(
        default=None,
        description="For REPOST type: original post ID (collapses repost chains to the root).",
    )
    deleted_at: datetime | None = Field(
        default=None,
        description="Timestamp of soft deletion. Post is permanently removed after 30 days.",
    )
    is_liked: bool = Field(
        default=False,
        description="True when the authenticated requester has liked this post.",
    )
    is_bookmarked: bool = Field(
        default=False,
        description="True when the authenticated requester has bookmarked this post.",
    )
    created_at: datetime
    updated_at: datetime


class PostVersionResponse(BaseModel):
    """Immutable snapshot of a post's content taken before each edit."""

    model_config = ConfigDict(from_attributes=True)

    version_id: UUID
    post_id: UUID
    version_number: int = Field(description="Post version at time of snapshot.")
    title: str | None
    body: str | None
    media_urls: dict | None
    link_preview: dict | None
    edited_by: UUID = Field(description="User ID who made this edit.")
    created_at: datetime = Field(description="When the snapshot was recorded.")


class PostListResponse(BaseModel):
    """Cursor-paginated list of posts."""

    items: list[PostResponse]
    next_cursor: str | None = Field(
        default=None,
        description="Opaque cursor string. Pass as `cursor` param to fetch the next page.",
    )
    has_more: bool = Field(description="True when additional pages exist.")


# ---------------------------------------------------------------------------
# Admin response schemas
# ---------------------------------------------------------------------------


class AdminPostListResponse(BaseModel):
    """Offset-paginated list of posts for admin views (all statuses)."""

    items: list[PostResponse]
    total: int = Field(description="Total number of matching posts.")
    page: int
    size: int


class AdminChannelListResponse(BaseModel):
    """Offset-paginated list of channels for admin views (including inactive)."""

    items: list[ChannelResponse]
    total: int = Field(description="Total number of channels.")
    page: int
    size: int
