"""create_content_schema

Revision ID: 31ff7a88983d
Revises: 001
Create Date: 2026-02-19 13:43:49.035502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '31ff7a88983d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocks_pair')
    )
    op.create_index('ix_blocks_blocked_id', 'blocks', ['blocked_id'], unique=False)
    op.create_index('ix_blocks_blocker_id', 'blocks', ['blocker_id'], unique=False)
    op.create_table('channels',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_channels_owner_id', 'channels', ['owner_id'], unique=False)
    op.create_index('ix_channels_slug', 'channels', ['slug'], unique=False)
    op.create_table('follows',
    sa.Column('follow_id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('follow_id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follows_pair')
    )
    op.create_index('ix_follows_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('ix_follows_following_id', 'follows', ['following_id'], unique=False)
    op.create_table('likes',
    sa.Column('like_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', postgresql.ENUM('POST', 'COMMENT', name='like_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_likes_user_target')
    )
    op.create_index('ix_likes_target', 'likes', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_likes_user_id', 'likes', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', postgresql.ENUM('USER', 'POST', 'COMMENT', 'WEBINAR', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'REVIEWED', 'ACTIONED', 'DISMISSED', name='report_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('ix_reports_reporter_id', 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_target', 'reports', ['target_type', 'target_id'], unique=False)
    op.create_table('posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content_type', postgresql.ENUM('TEXT', 'VIDEO', 'IMAGE', 'LINK', 'WEBINAR_CARD', 'COURSE_CARD', name='content_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'VERIFIED_ONLY', 'FOLLOWERS_ONLY', name='post_visibility'), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', 'DELETED', name='post_status'), nullable=False),
    sa.Column('specialty_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index('ix_posts_author_id', 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_fts', 'posts', [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_specialty_tags', 'posts', ['specialty_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_status', 'posts', ['status'], unique=False)
    op.create_table('bookmarks',
    sa.Column('bookmark_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_bookmarks_user_post')
    )
    op.create_index('ix_bookmarks_post_id', 'bookmarks', ['post_id'], unique=False)
    op.create_index('ix_bookmarks_user_id', 'bookmarks', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'HIDDEN', 'DELETED', name='comment_status'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_table('shares',
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id')
    )
    op.create_index('ix_shares_post_id', 'shares', ['post_id'], unique=False)
    op.create_index('ix_shares_user_id', 'shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shares_user_id', table_name='shares')
    op.drop_index('ix_shares_post_id', table_name='shares')
    op.drop_table('shares')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_bookmarks_user_id', table_name='bookmarks')
    op.drop_index('ix_bookmarks_post_id', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index('ix_posts_status', table_name='posts')
    op.drop_index('ix_posts_specialty_tags', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_fts', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_author_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_reports_target', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_reporter_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_likes_user_id', table_name='likes')
    op.drop_index('ix_likes_target', table_name='likes')
    op.drop_table('likes')
    op.drop_index('ix_follows_following_id', table_name='follows')
    op.drop_index('ix_follows_follower_id', table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_channels_slug', table_name='channels')
    op.drop_index('ix_channels_owner_id', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_blocks_blocker_id', table_name='blocks')
    op.drop_index('ix_blocks_blocked_id', table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
