"""create course LMS tables

Revision ID: 856d8eddef4e
Revises: 001
Create Date: 2026-02-20 12:47:56.766888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '856d8eddef4e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('instructor_name', sa.String(length=200), nullable=False),
    sa.Column('instructor_bio', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('specialty_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pricing_type', postgresql.ENUM('FREE', 'PAID', name='pricing_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('preview_video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.Column('completion_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_modules', sa.SmallInteger(), nullable=False),
    sa.Column('total_duration_mins', sa.Integer(), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='course_status'), nullable=False),
    sa.Column('visibility', postgresql.ENUM('PUBLIC', 'VERIFIED_ONLY', name='course_visibility'), nullable=False),
    sa.Column('scorm_package_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_courses_category', 'courses', ['category'], unique=False)
    op.create_index('ix_courses_created_at', 'courses', ['created_at'], unique=False)
    op.create_index('ix_courses_fts', 'courses', [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_courses_instructor_id', 'courses', ['instructor_id'], unique=False)
    op.create_index('ix_courses_specialty_tags', 'courses', ['specialty_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_table('course_modules',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_index('ix_course_modules_course_id', 'course_modules', ['course_id'], unique=False)
    op.create_table('lessons',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('lesson_type', postgresql.ENUM('VIDEO', 'PDF', 'TEXT', 'QUIZ', 'SCORM', name='lesson_type'), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_index('ix_lessons_module_id', 'lessons', ['module_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('progress_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'DROPPED', name='enrollment_status'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_lesson_id', sa.UUID(), nullable=True),
    sa.Column('last_position_secs', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_lesson_id'], ['lessons.lesson_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrollments_user_course')
    )
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_index('ix_enrollments_created_at', 'enrollments', ['created_at'], unique=False)
    op.create_index('ix_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_user_id', 'enrollments', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passing_score', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index('ix_quizzes_lesson_id', 'quizzes', ['lesson_id'], unique=False)
    op.create_table('certificates',
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=False),
    sa.Column('qr_verification_code', sa.String(length=100), nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('enrollment_id'),
    sa.UniqueConstraint('qr_verification_code')
    )
    op.create_index('ix_certificates_course_id', 'certificates', ['course_id'], unique=False)
    op.create_index('ix_certificates_user_id', 'certificates', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='lesson_progress_status'), nullable=False),
    sa.Column('watch_duration_secs', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.SmallInteger(), nullable=True),
    sa.Column('quiz_attempts', sa.SmallInteger(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_lesson_progress_enrollment_lesson')
    )
    op.create_index('ix_lesson_progress_enrollment_id', 'lesson_progress', ['enrollment_id'], unique=False)
    op.create_index('ix_lesson_progress_lesson_id', 'lesson_progress', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_progress_lesson_id', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_enrollment_id', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index('ix_certificates_user_id', table_name='certificates')
    op.drop_index('ix_certificates_course_id', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_quizzes_lesson_id', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_enrollments_user_id', table_name='enrollments')
    op.drop_index('ix_enrollments_status', table_name='enrollments')
    op.drop_index('ix_enrollments_created_at', table_name='enrollments')
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_lessons_module_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_course_modules_course_id', table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_specialty_tags', table_name='courses', postgresql_using='gin')
    op.drop_index('ix_courses_instructor_id', table_name='courses')
    op.drop_index('ix_courses_fts', table_name='courses', postgresql_using='gin')
    op.drop_index('ix_courses_created_at', table_name='courses')
    op.drop_index('ix_courses_category', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
